### PR TITLE
Fix api env variable port parsing

### PR DESCRIPTION
**Pull request by madninja**

### CODE REVIEW

**Comment by shawaj** [comment]
@madninja is there a rough ETA on when this will make it to a release?

**Review by JayKickliter — APPROVED** [review]
I confirmed that fixes the problem on OG hotspots with no surrounding setup changes

**Review by JayKickliter — CHANGES_REQUESTED** [review]
Scratch that. Something weird is happening. Let me investigate

**Review by JayKickliter — APPROVED** [review]
This works now
```
# podman ps
CONTAINER ID  IMAGE                                                  COMMAND               CREATED         STATUS             PORTS       NAMES
0edce583429d  quay.io/team-helium/test-images:gateway-PR416-dd193c3  helium_gateway se...  51 seconds ago  Up 51 seconds ago              miner
# podman exec miner helium_gateway info region
{
  "region": "US915"
}
```

**Pull request merged**
