### PR TITLE
target: add support for arm-openwrt-linux-muslgnueabi target

### PR DESCRIPTION
**Pull request by shawaj**
add build for arm-openwrt-linux-muslgnueabi target for bobcat light gateway

Relates-to: #80
Signed-off-by: Aaron Shaw <shawaj@gmail.com>

### CODE REVIEW

**Comment by madninja** [comment]
@shawaj Isn't openwrt maybe a bit too generic? All the other platforms represent a hardware/os target whereas openwrt is just the OS target and is assuming arm/muslgnueabi

**Comment by shawaj** [comment]
@madninja yeah probably. Maybe wait for @JackeyTY to test and then just change it to bobcat?

Or do you have another suggestion for the name?

**Comment by madninja** [comment]
> @madninja yeah probably. Maybe wait for @JackeyTY to test and then just change it to bobcat?
> 
> Or do you have another suggestion for the name?

I would suggest changing it to bobcat so we can keep moving ahead? @JackeyTY can change it when they get a chance

**Comment by JackeyTY** [comment]
so just changing the name to arm-bobcat-linux-muslgnueabi?

**Comment by madninja** [comment]
> so just changing the name to arm-bobcat-linux-muslgnueabi?

no change the name to `bobcat` since we name platforms as the overarching name without the specific build triplet

**Comment by madninja** [comment]
> @madninja yeah probably. Maybe wait for @JackeyTY to test and then just change it to bobcat?
> 
> Or do you have another suggestion for the name?

Would you be able to change the name to bobcat in your PR here @shawaj ?

**Comment by shawaj** [comment]
Will do this evening 👍

**Comment by shawaj** [comment]
@madninja all updated now

**Comment by madninja** [comment]
@shawaj it looks like the target triplet is not correctly specced here. Did you use a correct cross variant?

**Comment by madninja** [comment]
@shawaj are we still interested in this PR? May as well close I if it is no longer needed

**Comment by shawaj** [comment]
Will close, easy enough to reopen similar if necessary

**Pull request closed without merging**
