### PR TITLE
Avoid reusing ingest connections by creating a new one each time

### PR DESCRIPTION
**Pull request by Vagabond**

### CODE REVIEW

**Review by jeffgrunewald — COMMENTED** [review]
did we also want this to retry on failure for any amount/number of times?

assuming tonic automatically does the right thing when these ephemeral client's are dropped and closes all the connections we're trying to stop reusing.

**Comment by Vagabond** [comment]
we certainly can do a retry, but this was more about preventing the reuse problem to begin with, which it seems to do in testing.

**Review by jeffgrunewald — APPROVED** [review]

**Review by madninja — APPROVED** [review]
This looks good.. Ideally there'd be a corresponding issue to request queued beacon and witness reports?

**Comment by jeffgrunewald** [comment]
> This looks good.. Ideally there'd be a corresponding issue to request queued beacon and witness reports?

You mean a GitHub issue to add this feature to the local grpc api?

**Comment by madninja** [comment]
> > This looks good.. Ideally there'd be a corresponding issue to request queued beacon and witness reports?
> 
> You mean a GitHub issue to add this feature to the local grpc api?

No sorry that was confusing.. an issue, but an issue to add _queued_ witness/beacon report submission in case the hotspot fails to deliver

**Comment by jeffgrunewald** [comment]
> > > This looks good.. Ideally there'd be a corresponding issue to request queued beacon and witness reports?
> > 
> > 
> > You mean a GitHub issue to add this feature to the local grpc api?
> 
> No sorry that was confusing.. an issue, but an issue to add _queued_ witness/beacon report submission in case the hotspot fails to submit the beacon or witness report

Why don’t we take 10 min tomorrow to figure out what the parameters for this are and I’ll write it up

**Pull request merged**
