### PR TITLE
Add Cotx-Networks Package

### PR DESCRIPTION
**Pull request by cotxliang**

### CODE REVIEW

**Comment by cotxliang** [comment]
I added the deb package in my fork:
https://github.com/cotxliang/gateway-rs/releases/tag/v1.0.0-alpha.13

**Comment by madninja** [comment]
Can you add this to the [build matrix](https://github.com/helium/gateway-rs/blob/main/.github/workflows/ci.yml)

**Comment by cotxliang** [comment]
> Can you add this to the [build matrix](https://github.com/helium/gateway-rs/blob/main/.github/workflows/ci.yml)



> Can you add this to the [build matrix](https://github.com/helium/gateway-rs/blob/main/.github/workflows/ci.yml)

OK!  I have submitted the build matrix request.

**Comment by cotxliang** [comment]
> Can you add this to the [build matrix](https://github.com/helium/gateway-rs/blob/main/.github/workflows/ci.yml)

OK! I have submitted the build matrix request.

**Comment by madninja** [comment]
> > Can you add this to the [build matrix](https://github.com/helium/gateway-rs/blob/main/.github/workflows/ci.yml)
> 
> OK! I have submitted the build matrix request.

Please do it as part of this PR so we can see it work

**Comment by cotxliang** [comment]
> > > Can you add this to the [build matrix](https://github.com/helium/gateway-rs/blob/main/.github/workflows/ci.yml)
> > 
> > 
> > OK! I have submitted the build matrix request.
> 
> Please do it as part of this PR so we can see it work

Thanks, I've added to this branch.

**Pull request merged**
