### PR TITLE
Add deb package for x86_64

### PR DESCRIPTION
**Pull request by PaulVMo**
Created profile for x86_64 .deb package. For x86_64, I overwrote the listen addr in settings.toml to 0.0.0.0 instead of 127.0.0.1 as I am assuming many installs of the x86 package will be used with an external lorawan gateway versus on the lorawan gateway. Tested on an Ubuntu 20.04 amd64 server with a Dragino lps8 packet forwarded pointed to it. Successfully received join requests and uplinks, and send downlinks.

### CODE REVIEW

**Comment by syadnom** [comment]
PaulVMo, any chance I can get a copy of that build?

**Comment by PaulVMo** [comment]
Sure. I added the binary as a release in my fork:
https://github.com/PaulVMo/gateway-rs/releases/tag/x86

**Comment by syadnom** [comment]
Got it and installed it.    Unfortunately my mikrotik gateways aren't working.  Looks like they are sending a packet gateway-rs doesn't understand.  dang.

**Comment by madninja** [comment]
If you could rebase this it should fix the build and be ready to roll

**Review by madninja — COMMENTED** [review]
Did this PR delete Cargo.lock?

**Comment by PaulVMo** [comment]
Sorry about that. User error while resolving a conflict when rebasing. I'll
fix that.

**Pull request merged**
